### ISSUE TITLE
Usage of the maze in printables for sale

### ISSUE THREAD

**Issue by MaydayGD** [daleobrien/maze#5]
Hello,
I tried to figure out how to contact you but there is just no way. I was suggested to just use the issue report tab to write a note. Sorry if this is wrong.

I am creating (hand drawn) and selling different kinds of mazes to teachers and in my kid's activity books (printed worksheets). 
I found your maze generator and I would like to know can it be used commercially (to generate and make mazes for sale)? The MIT license added suggests it is OK, but want to make sure.

Also since this is not a program that can work on Windows and export mazes with solutions easily I was going to hire someone to turn the maze generator into a Windows application where you can pick the settings and have software export X number of mazes and solution files in SVG. 

Please let me know how you stand on this before I hire and pay someone for the job.

Thank you.

**Comment by daleobrien** [comment]
Yes, it's free and there are no commercial restrictions.
